In [1]:
import pandas as pd
import re

In [2]:
test_df = pd.read_csv("../data/test_raw.csv", encoding='utf-8', on_bad_lines='warn')
test_df.head()

,Master_Index,County,Health level,Years of Experience,Prompt,Nursing Competency,Clinical Panel
0,ID_CUAOY,Uasin Gishu,Sub-county Hospitals and Nursing Homes,2.0,I am a nurse with 2 years of experience in Gen...,Adult Health,SURGERY (ENT)
1,ID_OGSAY,Kiambu,Sub-county Hospitals and Nursing Homes,22.0,I am a nurse with 22 years of experience in Ge...,Child Health,SURGERY
2,ID_TYHSA,Uasin Gishu,National Referral Hospitals,NaN,I am a nurse working in a National Referral Ho...,General Emergency,INTERNAL MEDICINE
3,ID_CZXLD,Kakamega,Dispensaries and Private Clinics,NaN,I am a nurse working in a Dispensaries and Pri...,Child Health,PAEDIATRICS
4,ID_ZJQUQ,Kakamega,Health centres,NaN,I am a nurse working in a Health centres in Ka...,Child Health,PAEDIATRICS

In [3]:
def clean_text_advanced(text):
    if pd.isna(text):
        return ""
    text = str(text)
    text = re.sub(r'_x000D_|_x0001_|\\n|\\t', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

for col in ['Prompt', 'Clinical Panel', 'County']:
    if col in test_df.columns:
        test_df[f"{col}_clean"] = test_df[col].apply(clean_text_advanced)
    else:
        print(f"Warning: Column '{col}' not found in test dataset.")

test_df[['Prompt_clean', 'Clinical Panel_clean']].head()

                                        Prompt_clean Clinical Panel_clean
0  I am a nurse with 2 years of experience in Gen...        SURGERY (ENT)
1  I am a nurse with 22 years of experience in Ge...              SURGERY
2  I am a nurse working in a National Referral Ho...    INTERNAL MEDICINE
3  I am a nurse working in a Dispensaries and Pri...          PAEDIATRICS
4  I am a nurse working in a Health centres in Ka...          PAEDIATRICS

In [4]:
test_structured = pd.DataFrame()
test_structured['input_text'] = "CLINICAL CASE: " + test_df['Prompt_clean']
test_structured['target_text'] = ""  
test_structured['master_index'] = test_df['Master_Index']
test_structured['clinical_panel'] = test_df['Clinical Panel_clean']

test_structured.head()

,input_text,target_text,master_index,clinical_panel
0,CLINICAL CASE: I am a nurse with 2 years of ex...,,ID_CUAOY,SURGERY (ENT)
1,CLINICAL CASE: I am a nurse with 22 years of e...,,ID_OGSAY,SURGERY
2,CLINICAL CASE: I am a nurse working in a Natio...,,ID_TYHSA,INTERNAL MEDICINE
3,CLINICAL CASE: I am a nurse working in a Dispe...,,ID_CZXLD,PAEDIATRICS
4,CLINICAL CASE: I am a nurse working in a Healt...,,ID_ZJQUQ,PAEDIATRICS

In [5]:
output_path = "../data/test_structured_for_eval.csv"
test_structured.to_csv(output_path, index=False, encoding='utf-8')

print(f"Preprocessed test dataset saved to: {output_path}")
print(f"Shape: {test_structured.shape}")

Preprocessed test dataset saved to: ../data/test_structured_for_eval.csv
Shape: (100, 4)